openapi: 3.0.3
info:
  title: Product Reviews Simulation API
  version: 1.0.0-SNAPSHOT
paths:
  /simulate:
    summary: Generate orders
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              Clothing Catalogue:
                value:
                  catalogue: clothing
              Bags Catalogue:
                value:
                  catalogue: bags
              Utensils Catalogue:
                value:
                  catalogue: utensils
              Fashion accessory Catalogue:
                value:
                  catalogue: fashion accessory
              Electronics Catalogue:
                value:
                  catalogue: electronics
              Sports equipment Catalogue:
                value:
                  catalogue: sports equipment
              Office supplies Catalogue:
                value:
                  catalogue: office supplies
        required: true
      tags:
        - Simulator Resource
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Server error
